dist: precise
language: php

php:
  - 7.2

services:
  - postgresql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
