dist: xenial
language: php

php:
  - 7.2

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
  - cat storage/logs/laravel.log
