language: php

php:
  - 7.2

addons:
  postgresql: "9.4"

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
  - cat storage/logs/laravel.log
